# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool: sonic-mgmt-westus2-1es
variables:
- group: vg-storage-westus2

jobs:
- template: ../templates/publish-debian-mirror-jobs.yml
  parameters:
    mirrorType: "aptly"
